### ISSUE TITLE
Geliştirme Önerileri

### ISSUE THREAD

**Issue by OmerFI** [NRB-XZO/nrb_wifi_tool#1]
1- requirements.txt oluşturmalısın. Projede kullanılan modüllerin hepsi standard library den değil yani manuel olarak indirmeleri gerek. Her çalıştırdıklarında hata alıp verilen modülü indirmek yerine sadece bir kez "pip install -r requirements.txt" yapmaları daha güzel.
2- Proje python3 ile yazılmış ancak sen "python" kullan yazmışsın. Kali'de python --version yazarsan aslında kullanacakları python sürümünün python3 değil python2 olduğunu görürsün. Eğer python2 kullandırırsan insanlara hata çıkması muhtemeldir.
3- Fonksiyonların açıklamalarını fonksiyonların hemen bir satır altına yazmışsın. Eğer onları 3 lü tırnak aralarına alıp ("""açıklama""") fonksiyonun altına (1.satıra) yazarsan, docstring kurallarına daha iyi uymuş olursun. Detaylı bilgi için "docstring" kavramını araştırmanı tavsiye ederim.
4- Terminalde renkli yazdırmak için gereken kodları manuel olarak yazmışsın. Ama bunu daha kolay, anlaşılır, verimli yapan kütüphaneler var örneğin colorama, termcolor. Bunları kullanmanı tavsiye ederim

**Comment by NRB-XZO** [comment]
> 1- Required.txt oluşturmalısın. Projede kullanılan modüllerin hepsi standart kütüphane den değil yani manuel olarak indirmeleri gerek. Her çalıştırdıklarında hata alını indirmek yerine sadece bir kez "pip install -r requirements.txt" yapmaları daha güzel.
> 2- Proje python3 ile yazılmış ancak sen "python" kullan yazmışsın. Kali'de python --version yazarsan aslında kullanacakları python sürümünün python3 değil python2 olduğunu görürsün. Eğer python2 kullandırırsan insanlara hata çıkması muhtemeldir.
> 3- Fonksiyonların açıklamalarını fonksiyonların hemen bir satır altına yazmışsın. Eğer onları 3 lü tırnak aralarına alıp ("" açıklama "" ") fonksiyonun altına (1.satıra) yazarsan, docstring kurallarına daha iyi uymuş olursun. Detaylı bilgi için "
> 4- Terminalde renkli okunmak için gereken kodları manuel olarak yazmışsın. Ama bunu daha kolay, anlaşılır, yazılan dersler var colorama, termcolor. Bunları kullanmanı tavsiye ederim

Geri bildirimin için minnettarım ve düşüncelerini dikkate alacam.
